name: Deploy to shinyapps.io

on:
  push:
    tags:
      - v*.*.*
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Adjust this to match your app's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rsconnect-python  # Add other dependencies your app needs

    - name: Configure rsconnect
      run: |
        rsconnect add --account ${{ vars.SHINYAPPS_USERNAME }} --name rsconnect-server --token ${{ secrets.SHINYAPPS_TOKEN }} --secret ${{ secrets.SHINYAPPS_SECRET }}
    
    - name: Deploy to rsconnect # app-id parameter allows reliable overwriting of app content without creating duplicate apps.
      run: |
        rsconnect deploy shiny --app-id ${{ secrets.APP_ID }} ./ --name rsconnect-server  --title choose-adventure
